//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.ThongTinBangNhaps = new HashSet<ThongTinBangNhap>();
        }
    
        public int Id { get; set; }
        public string TenTaiKhoan { get; set; }
        public string HoVaTen { get; set; }
        public string MatKhau { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public System.DateTime NgayTao { get; set; }
        public int IdRoleTaiKhoan { get; set; }
    
        public virtual RoleTaiKhoan RoleTaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinBangNhap> ThongTinBangNhaps { get; set; }
    }
}
