//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinBangXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinBangXuat()
        {
            this.ThongTinBangXuat1 = new HashSet<ThongTinBangXuat>();
        }
    
        public string Id { get; set; }
        public string IdVatTu { get; set; }
        public string IdThongTinBangXuat { get; set; }
        public int IdKhachHang { get; set; }
        public Nullable<int> Count { get; set; }
        public string Status { get; set; }
        public double GiaXuat { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinBangXuat> ThongTinBangXuat1 { get; set; }
        public virtual VatTu VatTu { get; set; }
        public virtual BangXuat BangXuat { get; set; }
    }
}
