//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinBangNhap
    {
        public string Id { get; set; }
        public string IdVatTu { get; set; }
        public string IdBangNhap { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public string TrangThai { get; set; }
    
        public virtual BangNhap BangNhap { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
